### ISSUE TITLE
Not solving for the temperature field

### ISSUE THREAD

**Issue by akhoubani** [exabl/snek5000-cbox#1]
Hi,

It does not solve for the temperature field. I checked the log file and I noticed that it only reads field 1 (velocity) boundary conditions and it does not activate IFHEAT. 

> cbox.re2                                            
 partioning elements to MPI ranks
 reading mesh 
 reading bc for ifld           1
 done :: read .re2 file    0.18E-02 sec

I tried to compile it manually. The same result!

When I added [TEMPERATURE] key in the .par file, it worked perfectly (manually). 

> cbox.re2                                            
 partioning elements to MPI ranks
 reading mesh 
 reading bc for ifld           1
 reading bc for ifld           2
 done :: read .re2 file    0.20E-02 sec

The [TEMPERATURE] key is disabled by default in snek5000. I wonder if it is possible to enable it.

Thanks.

**Comment by paugier** [comment]
Could you give us exactly what you had to add and where?

**Comment by akhoubani** [comment]
In the .par file, I added:

> [TEMPERATURE]
rhoCp = 1.0
conductivity = 1.0 
residualtol = 1e-8

Then I compiled it with `makenek`.

**Comment by paugier** [comment]
I think it is fixed by exabl/snek5000#42 and https://github.com/exabl/snek5000-cbox/commit/a2d0aafafbff57cd70e047154fbc73adeedc5971

Could you please check ?

**Comment by akhoubani** [comment]
It has the same result as before. It doesn't add those lines to the .par file.

**Comment by paugier** [comment]
I get:

```
[PRESSURE]
residualProj = no
writeToFieldFile = yes
preconditioner = semg_xxt

[TEMPERATURE]
residualTol = 1e-08
residualProj = no
writeToFieldFile = yes
solver = helm
advection = yes
conjugateHeatTransfer = no
conductivity = 1.0
rhoCp = 1.0
```
So I guess it is fixed. You have to update both nek5000 (branch fix-InfoSolver) and snek5000-cbox.

**Comment by akhoubani** [comment]
Yes, I got it. Thanks.
